---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: jupyter-datarefinery-data
spec:
  storageClassName: nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100G