/* eslint-disable */
export const menus = [
  {
    "id": 21,
    "parentId": 0,
    "children": [
      {
        "id": 29,
        "parentId": 21,
        "children": [

        ],
        "menuName": "经济运行监测",
        "orderNum": 1,
        "path": "/economy-monitor",
        "component": "",
        "queryParam": "",
        "menuType": "M",
        "visible": false,
        "status": false,
        "perms": "jjyxjc",
        "icon": "#",
        "relationType": "none",
        "allowsDataRange": true,
        "createBy": 0,
        "createTime": "2023-09-08 11:37:46",
        "updateBy": 0,
        "updateTime": "2023-09-08 11:37:46"
      },
      {
        "id": 2,
        "parentId": 21,
        "children": [

        ],
        "menuName": "经济指标归因",
        "orderNum": 2,
        "path": "/economy-target",
        "component": "",
        "queryParam": "",
        "menuType": "M",
        "visible": false,
        "status": false,
        "perms": "jjzbgy",
        "icon": "#",
        "relationType": "none",
        "allowsDataRange": false,
        "createBy": 0,
        "createTime": "2023-07-03 04:30:38",
        "updateBy": 0,
        "updateTime": "2023-07-03 04:30:38"
      },
      {
        "id": 3,
        "parentId": 21,
        "children": [

        ],
        "menuName": "经济指数分析",
        "orderNum": 3,
        "path": "/economy-index",
        "component": "",
        "queryParam": "",
        "menuType": "M",
        "visible": false,
        "status": false,
        "perms": "jjzsfx",
        "icon": "#",
        "relationType": "index",
        "allowsDataRange": true,
        "createBy": 0,
        "createTime": "2023-07-03 04:31:16",
        "updateBy": 0,
        "updateTime": "2023-07-03 04:31:16",
        "indexes": [
          {
            "id": 10000,
            "name": "数字产业发展指数",
            "code": "szcyfzzs"
          }
        ]
      }
    ],
    "menuName": "宏观经济",
    "orderNum": 1,
    "path": "/21",
    "component": "",
    "queryParam": "",
    "menuType": "M",
    "visible": false,
    "status": false,
    "perms": "hgjj-xx",
    "icon": "#",
    "relationType": "none",
    "allowsDataRange": true,
    "createBy": 0,
    "createTime": "2023-07-03 05:04:56",
    "updateBy": 0,
    "updateTime": "2023-07-03 05:04:56"
  },
  {
    "id": 22,
    "parentId": 0,
    "children": [
      {
        "id": 4,
        "parentId": 22,
        "children": [],
        "menuName": "产业结构分析",
        "orderNum": 1,
        "path": "/structural-analysis",
        "component": "",
        "queryParam": "",
        "menuType": "M",
        "visible": false,
        "status": false,
        "perms": "cyjgfx",
        "icon": "#",
        "relationType": "none",
        "allowsDataRange": true,
        "createBy": 0,
        "createTime": "2023-07-03 04:31:59",
        "updateBy": 0,
        "updateTime": "2023-07-03 04:31:59"
      },
      {
        "id": 9,
        "parentId": 22,
        "children": [],
        "menuName": "产业链图谱",
        "orderNum": 2,
        "path": "/industry-map",
        "component": "",
        "queryParam": "",
        "menuType": "M",
        "visible": false,
        "status": false,
        "perms": "cyltp",
        "icon": "#",
        "relationType": "chain",
        "allowsDataRange": true,
        "createBy": 0,
        "createTime": "2023-07-03 05:02:16",
        "updateBy": 0,
        "updateTime": "2023-07-03 05:02:16",
        "chains": []
      },
      {
        "id": 28,
        "parentId": 22,
        "children": [

        ],
        "menuName": "产业综合对比",
        "orderNum": 3,
        "path": "/comprehensive-comparison",
        "component": "",
        "queryParam": "",
        "menuType": "M",
        "visible": false,
        "status": false,
        "perms": "cyzhdb",
        "icon": "#",
        "relationType": "chain",
        "allowsDataRange": true,
        "createBy": 0,
        "createTime": "2023-07-03 05:02:16",
        "updateBy": 0,
        "updateTime": "2023-07-03 05:02:16",
        "chains": []
      }
    ],
    "menuName": "产业分析",
    "orderNum": 2,
    "path": "/22",
    "component": "",
    "queryParam": "",
    "menuType": "M",
    "visible": false,
    "status": false,
    "perms": "cyfx-xk",
    "icon": "#",
    "relationType": "none",
    "allowsDataRange": true,
    "createBy": 0,
    "createTime": "2023-07-03 05:05:20",
    "updateBy": 0,
    "updateTime": "2023-07-03 05:05:20"
  },
  {
    "id": 23,
    "parentId": 0,
    "children": [

    ],
    "menuName": "产业招商",
    "orderNum": 3,
    "path": "/industrial-investment",
    "component": "",
    "queryParam": "",
    "menuType": "F",
    "visible": false,
    "status": false,
    "perms": "cyzs-xb",
    "icon": "#",
    "relationType": "none",
    "allowsDataRange": true,
    "createBy": 0,
    "createTime": "2023-07-03 05:06:08",
    "updateBy": 0,
    "updateTime": "2023-07-03 05:06:08"
  },
  {
    "id": 19,
    "parentId": 0,
    "children": [
      {
        "id": 26,
        "parentId": 19,
        "children": [

        ],
        "menuName": "政策查询",
        "orderNum": 1,
        "path": "/policy-inquiries",
        "component": "",
        "queryParam": "",
        "menuType": "M",
        "visible": false,
        "status": false,
        "perms": "zccx-1",
        "icon": "#",
        "relationType": "none",
        "allowsDataRange": true,
        "createBy": 0,
        "createTime": "2023-07-03 05:07:00",
        "updateBy": 0,
        "updateTime": "2023-07-03 05:07:00"
      },
      {
        "id": 27,
        "parentId": 19,
        "children": [

        ],
        "menuName": "政策匹配",
        "orderNum": 2,
        "path": "/policy-documents",
        "component": "",
        "queryParam": "",
        "menuType": "M",
        "visible": false,
        "status": false,
        "perms": "zcwj-1",
        "icon": "#",
        "relationType": "none",
        "allowsDataRange": true,
        "createBy": 0,
        "createTime": "2023-07-03 05:07:00",
        "updateBy": 0,
        "updateTime": "2023-07-03 05:07:00"
      }
    ],
    "menuName": "产业政策",
    "orderNum": 4,
    "path": "/19",
    "component": "",
    "queryParam": "",
    "menuType": "M",
    "visible": false,
    "status": false,
    "perms": "cyzc",
    "icon": "#",
    "relationType": "none",
    "allowsDataRange": true,
    "createBy": 0,
    "createTime": "2023-07-03 05:07:00",
    "updateBy": 0,
    "updateTime": "2023-07-03 05:07:00"
  }
]